# Generated by Django 4.2.6 on 2023-10-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'الملف الشخصي', 'verbose_name_plural': 'ملفات شخصية'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=40, verbose_name='الاسم '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(verbose_name='سعر الكشف '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_iam',
            field=models.TextField(max_length=250, verbose_name='من انا '),
        ),
    ]
