# Generated by Django 4.2.6 on 2023-10-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/defaults/profile.jpg', upload_to='profile', verbose_name='الصورة الشخصية'),
        ),
    ]
