# Generated by Django 4.2.6 on 2023-10-15 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_facebook_profile_google_profile_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
