# Generated by Django 4.2.6 on 2023-10-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_create_at_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'انثى')], default='male', max_length=10, verbose_name='الجنس'),
        ),
    ]
