# Generated by Django 4.2.6 on 2023-10-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialist',
            field=models.CharField(choices=[('جلدية', 'جلدية'), ('اسنان', 'اسنان'), ('اطفال حديثي الولاد', 'اطفال حديثي الولاد'), ('مخ واعصاب', 'مخ واعصاب'), ('عظام', 'عظام'), ('نساء', 'نساء'), ('انف واذن وحنجرة', 'انف واذن وحنجرة'), ('قلب واوعية دموية', 'قلب واوعية دموية'), ('امراض دم', 'امراض دم'), ('جراحه', 'جراحه'), ('تجميل', 'تجميل')], default='جلدية', max_length=50, verbose_name='التخصص'),
        ),
    ]
