# Generated by Django 4.2.6 on 2023-10-21 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_profile_is_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_doctor',
        ),
        migrations.CreateModel(
            name='Profile_Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='الاسم ')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'انثى')], default='male', max_length=10, verbose_name='الجنس')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
